GET http://localhost:8080/api/address/1
###
POST http://localhost:8080/api/address
Content-Type: application/json

{
  "addressId": 11,
  "region": "sgs",
  "city": "afssaf",
  "nameOfStreet": "asfa",
  "number": 1
}
###
GET http://localhost:8080/api/person/145422544545